set -e
cd "$(dirname "$0")"

usage() {
	echo "Usage: $0 <command>"
	echo -e "\thelp: Show this menu\n\tdev: Run a local server for development.\n\tclean: Clean up any autogenerated files.\n\tbuild: Build the website for production."
}

if [ $# -eq 0 ]; then
	usage
	exit 1
fi

case "$1" in
"dev")
	hugo server
	;;
"clean")
	rm -rf public resources dist .hugo_build.lock
	echo "Cleaned up."
	;;
"build")
	echo "Building website..."
	hugo --gc --minify --templateMetrics --templateMetricsHints --buildDrafts --buildExpired --buildFuture --forceSyncStatic -d dist -e production >/dev/null
	echo "Done. Built to dist/"
	;;
"help"|"--help"|"-h")
	usage
	;;
*)
	echo "Invalid argument: $1"
	usage

	exit 1
	;;
esac
